need to save a copy of shumlib locally

diff --git a/usr/local/bin/install-um-extras-intel b/usr/local/bin/install-um-extras-intel
--- a/usr/local/bin/install-um-extras-intel
+++ b/usr/local/bin/install-um-extras-intel
@@ -118,6 +118,7 @@ LIBAEC_VERSION="1.1.3"
 ECCODES_VERSION="2.35.0"
 SHUMLIB_VERSION="13.0"
 OASIS_MCT_VERSION="5.1"
+SHUMLIB_SRC="$HOME/shumlib"
 
 export DEPS_DIR=/usr/local/intel
 
@@ -137,6 +138,14 @@ export HDF5=$DEPS_DIR
 export PNETCDF=$DEPS_DIR
 
 export LD_LIBRARY_PATH="$DEPS_DIR/lib:$LD_LIBRARY_PATH"
+
+# run some checks
+if [ ! -d $SHUMLIB_SRC ]; then
+  echo "ERROR: directory $SHUMLIB_SRC does not exist!"
+  echo "Download shumlib using command:"
+  echo "cd $HOME; fcm co fcm:shumlib.x/trunk@HEAD shumlib"
+  exit 1
+fi
 
 mkdir -p $DEPS_DIR
 mkdir -p ${DEPS_DIR}/bin
