getting shumlib to build

diff --git a/usr/local/bin/install-um-extras-intel b/usr/local/bin/install-um-extras-intel
--- a/usr/local/bin/install-um-extras-intel
+++ b/usr/local/bin/install-um-extras-intel
@@ -118,7 +118,10 @@ LIBAEC_VERSION="1.1.3"
 ECCODES_VERSION="2.35.0"
 SHUMLIB_VERSION="13.0"
 OASIS_MCT_VERSION="5.1"
-SHUMLIB_SRC="$HOME/shumlib"
+
+# TO CHANGE
+SHUMLIB_SRC="/home/pletzera/shumlib"
+GCOM_SRC="/home/pletzera/gcom"
 
 export DEPS_DIR=/usr/local/intel
 
@@ -144,6 +147,12 @@ if [ ! -d $SHUMLIB_SRC ]; then
   echo "ERROR: directory $SHUMLIB_SRC does not exist!"
   echo "Download shumlib using command:"
   echo "cd $HOME; fcm co fcm:shumlib.x/trunk@HEAD shumlib"
+  exit 1
+fi
+if [ ! -d $GCOM_SRC ]; then
+  echo "ERROR: directory $GCOM_SRC does not exist!"
+  echo "Download gcom using command:"
+  echo "cd $HOME; fcm co fcm:gcom.x/trunk@HEAD gcom"
   exit 1
 fi
 
