+ shumlib

diff --git a/usr/local/bin/install-um-extras-intel b/usr/local/bin/install-um-extras-intel
--- a/usr/local/bin/install-um-extras-intel
+++ b/usr/local/bin/install-um-extras-intel
@@ -281,6 +281,53 @@ make install
 cd ../..
 rm -rf eccodes-${ECCODES_VERSION}-Source
 
+# shumlib
+cd $DEPS_DIR
+fcm co fcm:shumlib.x/trunk@HEAD shumlib
+cd shumlib
+vm_config='ssec-ifort-icc'
+echo "Building Shumlib dependencies"
+
+# shumlib is built twice, with and without OpenMP:
+for shum_omp in true false; do
+    omp=no-openmp
+    if $shum_omp; then
+        omp=openmp
+    fi
+    install_dir="/usr/local/intel/shumlib/$vn/$vm_config/$omp"
+    mkdir -p "$install_dir"
+    # Remove any previous builds
+    make -f make/${vm_config}.mk clean > /dev/null 2>&1 
+    # Build the library
+    echo
+    echo "Building Shumlib $omp library..."
+    echo "Make output at $install_dir/make.log"
+    SHUM_OPENMP=$shum_omp make -f make/${vm_config}.mk &> "$install_dir/make.log"
+    if [ $? -ne 0 ]; then
+        echo "Shumlib $omp build failed."
+        exit 1
+    else
+        echo "Shumlib $omp build completed successfully."
+    fi
+    # Test the library
+    echo "Testing Shumlib $omp library..."
+    echo "Test output at $install_dir/test.log"
+    SHUM_OPENMP=$shum_omp make -f make/${vm_config}.mk test &> "$install_dir/test.log"
+    if [ $? -ne 0 ]; then
+        echo "Shumlib $omp tests failed."
+        exit 1
+    else
+        echo "Shumlib $omp built-in tests passed."
+    fi
+    # Copy the library to UMDIR
+    cp -r build/$vm_config/* $install_dir || echo "Failed to install Shumlib $omp library"
+done
+# Clean
+cd $DEPS_DIR
+rm -rf shumlib
+
+
+
 # # shumlib
 # cd $DEPS_DIR
 # wget https://github.com/metomi/shumlib/archive/refs/tags/um${SHUMLIB_VERSION}.tar.gz
